#!/usr/bin/env python3
r"""Generate src/macros/leandecls.tex: a declaration -> source-URL map for the
printable blueprint.

Scans every ``\lean{...}`` annotation in src/results/*.tex, locates each
declaration in the Lean sources under ../singular_moduli/, and emits one
``\leanurl@<decl>`` macro per declaration pointing at the file (with line
anchor) on the GitHub mirror.  Declarations that cannot be located are emitted
as comments so the print build still compiles (the name is then typeset
without a hyperlink).

Run from the blueprint/ directory:  python3 gen_leandecls.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_URL = "https://github.com/ElodinLaarz/lean-thesis/blob/main"

BLUEPRINT = Path(__file__).resolve().parent
REPO_ROOT = BLUEPRINT.parent
LEAN_ROOT = REPO_ROOT / "singular_moduli"
RESULTS = BLUEPRINT / "src" / "results"
OUT = BLUEPRINT / "src" / "macros" / "leandecls.tex"

DECL_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)*"
    r"(?:protected\s+|private\s+|noncomputable\s+|partial\s+|scoped\s+)*"
    r"(?:theorem|lemma|def|abbrev|structure|class|instance|inductive|opaque)\s+"
    r"([A-Za-z_][A-Za-z0-9_.']*)"
)
NS_RE = re.compile(r"^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.']*)\s*$")
END_RE = re.compile(r"^\s*end\s+([A-Za-z_][A-Za-z0-9_.']*)\s*$")


def index_lean_sources() -> dict[str, tuple[str, int]]:
    decls: dict[str, tuple[str, int]] = {}
    for path in sorted(LEAN_ROOT.rglob("*.lean")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        stack: list[str] = []
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            m = NS_RE.match(line)
            if m:
                stack.append(m.group(1))
                continue
            m = END_RE.match(line)
            if m and stack and stack[-1] == m.group(1):
                stack.pop()
                continue
            m = DECL_RE.match(line)
            if m:
                name = m.group(1)
                qual = ".".join([*stack, name]) if stack else name
                decls.setdefault(qual, (rel, lineno))
                decls.setdefault(name, (rel, lineno))
    return decls


def referenced_decls() -> list[str]:
    names: list[str] = []
    for tex in sorted(RESULTS.glob("*.tex")):
        for m in re.finditer(r"\\lean\{([^}]*)\}", tex.read_text(encoding="utf-8")):
            for name in m.group(1).split(","):
                name = name.strip()
                if name and name not in names:
                    names.append(name)
    return names


def main() -> int:
    index = index_lean_sources()
    lines = [
        "% AUTO-GENERATED by blueprint/gen_leandecls.py -- do not edit by hand.",
        "% Maps each \\lean{} declaration to its source URL on the GitHub mirror.",
        "\\begingroup",
        "\\catcode`\\_=12",
        "\\catcode`\\#=12",
    ]
    missing: list[str] = []
    for name in referenced_decls():
        hit = index.get(name)
        if hit is None:
            missing.append(name)
            lines.append(f"% MISSING: {name}")
            continue
        rel, lineno = hit
        url = f"{REPO_URL}/{rel}#L{lineno}"
        lines.append(
            "\\expandafter\\gdef\\csname leanurl@" + name + "\\endcsname{" + url + "}"
        )
    lines.append("\\endgroup")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}: "
          f"{len(referenced_decls()) - len(missing)} resolved, {len(missing)} missing")
    for name in missing:
        print(f"  MISSING {name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
