name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Mathlib Cache
        working-directory: ./singular_moduli
        run: lake exe cache get

      - name: Build Project
        working-directory: ./singular_moduli
        run: lake build
